### ISSUE TITLE
Duas perguntas com o mesmo nome!

### ISSUE THREAD

**Issue by muluma** [douglasjunior/aula-revisao-de-codigo#1]
A oitava e nona questão estão descriminada com o código 8.

1 - Lorem ipsum conubia nam etiam eget sollicitudin, massa tortor aenean consequat pulvinar libero conubia, lacu(...)
2 - Lorem ipsum conubia nam etiam eget sollicitudin, massa tortor aenean consequat pulvinar libero conubia, lacu(...)
(...) - Lorem ipsum conubia nam etiam eget sollicitudin, massa tortor aenean consequat pulvinar libero conubia, lacu(...)
**8 - oitava questão
8 - oitava questão**

**Comment by douglasjunior** [comment]
Thanks.
